#!/bin/bash

MAINFOLDER="${HOME}/.config/config-manager"
THEMESCONFIG="${MAINFOLDER}/themes"
FILESFOLDER="${MAINFOLDER}/files"

if [ $# -eq 0 ]
then
    if [ ! -d $MAINFOLDER ]
    then
        mkdir -p $MAINFOLDER
        touch ${HOME}/themes
        echo $FILESFOLDER > ${HOME}/themes
        mv ${HOME}/themes ${THEMESCONFIG}
    fi
    if [ ! -f $THEMESCONFIG ]
    then
        touch $THEMESCONFIG
        echo $FILESFOLDER > $THEMESCONFIG
        if [ ! -d $FILESFOLDER ]
        then
            mkdir -p $FILESFOLDER
        fi
    fi
fi
FILESFOLDER=$( head -n 1 $THEMESCONFIG )

if [ $# -eq 0 ]
then
    ls $FILESFOLDER

else
    LINE=$( grep -n "NAME|$1" $THEMESCONFIG | cut -d : -f1 )
    LENGTH=$( wc -l $THEMESCONFIG | cut -d ' ' -f1 )
    for (( ; ; ))
    do
        LINE=$((LINE+1))
        CURRENT=$( sed -n $LINE'p' $THEMESCONFIG )
        if [ $CURRENT == "END" ] || [ $LINE -gt $LENGTH ] ||
               [ $( cut -d \| -f1 <<< $CURRENT ) == "COMMAND" ]
        then
            break
        fi
        if [ $LINE -gt 100 ]
        then
            echo "forced end"
            break
        fi
        NAME=$( cut -d \| -f1 <<< $CURRENT )
        DESTINATION=$( cut -d \| -f2 <<< $CURRENT )
        cp -r $FILESFOLDER/$1/$NAME ~/$DESTINATION
    done
fi

if [[ $( cut -d \| -f1 <<< $CURRENT ) == "COMMAND" ]]
then
    COMMANDFILE=$( cut -d \| -f2 <<< $CURRENT )
    chmod +x $FILESFOLDER/$1/$COMMANDFILE
    exec $FILESFOLDER/$1/$COMMANDFILE
fi
