#!/bin/bash

MAINFOLDER="${HOME}/.config/config-manager"
CONFIG="${MAINFOLDER}/config"
FILESFOLDER="${MAINFOLDER}/files"

if [ $# -eq 0 ]
then
    if [ ! -d $MAINFOLDER ]
    then
        mkdir -p $MAINFOLDER
        touch ${CONFIG}
        echo $FILESFOLDER > ${CONFIG}
        mv ${HOME}/config ${CONFIG}
    fi
    if [ ! -f $CONFIG ]
    then
        touch $CONFIG
        echo $FILESFOLDER > $CONFIG
        if [ ! -d $FILESFOLDER ]
        then
            mkdir -p $FILESFOLDER
        fi
    fi
fi
FILESFOLDER=$( head -n 1 $CONFIG )

if [ $# -eq 0 ]
then
    ls $FILESFOLDER

else
    if [ ! -d $MAINFOLDER/backup ]
    then
        mkdir $MAINFOLDER/backup
    fi
    rm -rf $MAINFOLDER/backup/*
    FILES=1
    LINE=$( grep -n "NAME|$1" $CONFIG | cut -d : -f1 )
    LENGTH=$( wc -l $CONFIG | cut -d ' ' -f1 )
    for (( ; ; ))
    do
        LINE=$((LINE+1))
        CURRENT=$( sed -n $LINE'p' $CONFIG )
        if [ $CURRENT == "FILES" ]
        then
            FILES=1
            continue
        elif [ $CURRENT == "SUBDIRS" ]
        then
            FILES=0
            continue
        elif [ $( cut -d \| -f1 <<< $CURRENT ) == "NAME" ] || [ $LINE -gt $LENGTH ] ||
               [ $( cut -d \| -f1 <<< $CURRENT ) == "COMMAND" ]
        then
            break
        fi
        if [ $LINE -gt $LENGTH ]
        then
            echo "forced end"
            break
        fi
        NAME=$( cut -d \| -f1 <<< $CURRENT )
        DESTINATION=$( cut -d \| -f2 <<< $CURRENT )
        if [ $FILES -eq 1 ]
        then
            if [ -f ~/$DESTINATION ]
            then
                cp ~/$DESTINATION $MAINFOLDER/backup/$NAME
            fi
            cp $FILESFOLDER/$1/$NAME ~/$DESTINATION
        else
            if [ -d ~/$DESTINATION ]
            then
                cp -r ~/$DESTINATION $MAINFOLDER/backup/$NAME
            fi
            cp -r $FILESFOLDER/$1/$NAME ~/$DESTINATION
        fi
    done
fi

if [[ $( cut -d \| -f1 <<< $CURRENT ) == "COMMAND" ]]
then
    COMMANDFILE=$( cut -d \| -f2 <<< $CURRENT )
    chmod +x $FILESFOLDER/$1/$COMMANDFILE
    exec $FILESFOLDER/$1/$COMMANDFILE
fi
