* Introduction
As the name implies it's a simple configuration files manager. You can use it to quickly change your colorscheme or settings of your favorite program. It's entirely written in Bash and the only requirement is Rofi.
* Quick Start
To use it, you first need to give it execution permissions like that:
#+begin_src bash
chmod +x config-manager
#+end_src
To launch this script, you need to run the following command:
#+begin_src bash
rofi -show config-manager -modi "config-manager:/path/to/config-manager"
#+end_src
If you have no configuration folder and/or configuration files created, these will be automatically created at the first launch in *$HOME/.config/config-manager/*. Just to be on the safe side script automatically creates backup of the previous configuration in *$HOME/.config/config-manager/backup* with names corresponding to those specified in the *config* file.
* Configuration

* TODO TODO
- Add some templating instructions.
- Add the ability to run COMMAND file before copying files.
- Create cli version of the script.
- Create dmenu version of the script.
